### ISSUE TITLE
Lots of kicks for vehicle restrictions

### ISSUE THREAD

**Issue by iainlbc** [noxsicarius/Epoch-Admin-Tools#209]
Hey nox,

Great tool, we are spinning up a new dedi and going to be using this and BEC as primary admin tools

We're in the testing/alpha phase of this server and I've been getting a lot of kicked for vehicle restriction errors when spawning a heli or testing out spawning building parts. I've followed instructions pretty carefully and have the files in the battle eye folder/etc.

Anyways let me know how i can help testing further, or if you have any advice on resolving this. I kind of want to modify and strip alot of the options out, any vehicles that cause a kick/etc. -- but also i dont want to fork and drift far from your updates, especially with your 1.9 major rewrite coming up (do you still have time for such endeavors?) 

Also I am curious if you can provide any info on what if any additional attack vectors/risks are created by installing this mod & the battle eye filters needed for it to function? 

I think we'd prefer to do strip out any options that are going to allow for new exploits not possible without admin tools installed. 

Thanks again! Look forward to your response. Based on a few days research this seems like the best and most up to date admin tool available for a arma2 dayz epoch server

iain

**Comment by noxsicarius** [comment]
If you don't want all of the bells and whistles you can try Admin Tools Lite branch.

As for the kicks can you give me maybe 3 class names? I can try to figure out the issue.

I have a big update with around 20 file changes for efficiency and code cuts coming to the test branch soon. I am systematically making things as small as possible to eliminate redundant and costly code. The main delay has been the holiday and the start of a new school semester that I have to settle in to.

The only way for anyone to gain access to these is to have an admin UID. UID spoofing is quite hard to do now. I even wrote the dll using secure methods and closing all ports immediately after use so no one can inject into the dll socket. Version 2.0 of this will be even more secure since it will all be server side and no one will even be able to know you have it installed unless you tell them. I have been stripping out unnecessary code and setting things to only send info packets for certain things to admins/super admins to minimize risk as well. From what I understand there has not been an issue of someone gaining access to these admin tools.

**Comment by iainlbc** [comment]
Thanks for the fast response! I will check out the lite branch and happy to help QA your test branch when its ready as well, just shoot me a msg or comment on here

Cheers,
iain

**Comment by noxsicarius** [comment]
I will. There are a few updates to the test branch already, but nothing worth testing just yet. 1.9.2 is nearly ready. I just have a few things left.

**Comment by noxsicarius** [comment]
Commit 47119a3 is not associated with this issue.
