### ISSUE TITLE
Anti hack conflict with ESSv2

### ISSUE THREAD

**Issue by TheAgain** [noxsicarius/Epoch-Admin-Tools#268]
Hello, just wanted to let you know that the anti teleport portion of the anti hack cancels out the ground selection spawn option for the ESS mod. Just thought I'd let you know. Ended up having to disable the anti hack portion

**Comment by noxsicarius** [comment]
What error does it give

**Comment by TheAgain** [comment]
It does not give an error. What happens as far as i can tell from watching with ESP on is..
Player logs in, See there location on map in spawn zone in ocean
They chose male/female and are moved to shore where they would normally spawn.
ESS lets them chose loadout (works fine)  then they select ground or halo spawn
Halo spawn works correctly but ground spawn does not.
When ground is selected the player is moved to the location of there choice and then immediately moved back to the original default spawn location.
I have myself added to admins so it works correctly for me, guessing I am exempt from the script.

**Comment by noxsicarius** [comment]
This is caused by the antihack teleport. That mod must have a built in bypass for the original antihack by executing before the antihack, which doesn't seem to work with the antihack being located in my mod instead of the server files. My mod executes on both the server and client to catch all hacks even before they hit the server. It also removes the ability to teleport for anyone unless they are in a special exception list that must be passed through the server.

To fix with my mod, in ESS spawn.sqf, on line 10 add this:
_UID = (getPlayerUID player);
EAT_teleportFixServer = ["add",_UID];
publicVariableServer "EAT_teleportFixServer";

at the very end add this
EAT_teleportFixServer = ["remove",_UID];
publicVariableServer "EAT_teleportFixServer";

**Comment by TheAgain** [comment]
Can mark this as resolved! Thanks a bunch

**Comment by noxsicarius** [comment]
Good to know it worked. Don't have that mod so I didn't have a way to test it.
